/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package event.management2;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CS
 */
public class AddEmployee extends javax.swing.JInternalFrame {
int d;
String c;
    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
        
           Toolkit yk= Toolkit.getDefaultToolkit();
         int x=(int) yk.getScreenSize().getWidth();
         int y=(int) yk.getScreenSize().getHeight();
          //jLabel1.setSize(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label3 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label4 = new java.awt.Label();
        textArea1 = new java.awt.TextArea();
        label5 = new java.awt.Label();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        label6 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        label7 = new java.awt.Label();
        jPasswordField1 = new javax.swing.JPasswordField();
        label8 = new java.awt.Label();
        textField4 = new java.awt.TextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        label9 = new java.awt.Label();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Add Employee");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        label1.setBackground(new java.awt.Color(204, 204, 204));
        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("ADD EMPLOYEE");
        getContentPane().add(label1);
        label1.setBounds(390, 10, 149, 28);

        label2.setBackground(new java.awt.Color(204, 204, 204));
        label2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label2.setText("Name");
        getContentPane().add(label2);
        label2.setBounds(80, 80, 96, 19);

        textField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(textField1);
        textField1.setBounds(220, 70, 190, 30);

        label3.setBackground(new java.awt.Color(204, 204, 204));
        label3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label3.setText("Phone");
        getContentPane().add(label3);
        label3.setBounds(80, 130, 96, 19);

        textField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(textField2);
        textField2.setBounds(220, 120, 190, 30);

        label4.setBackground(new java.awt.Color(204, 204, 204));
        label4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label4.setText("Address");
        getContentPane().add(label4);
        label4.setBounds(80, 260, 96, 19);

        textArea1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(textArea1);
        textArea1.setBounds(220, 220, 190, 120);

        label5.setBackground(new java.awt.Color(204, 204, 204));
        label5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label5.setText("Gender");
        getContentPane().add(label5);
        label5.setBounds(80, 350, 70, 19);

        jRadioButton1.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("Female");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(310, 350, 93, 23);

        jRadioButton2.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("Male");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(220, 350, 70, 23);

        label6.setBackground(new java.awt.Color(204, 204, 204));
        label6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label6.setText("Username");
        getContentPane().add(label6);
        label6.setBounds(80, 400, 96, 19);

        textField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(textField3);
        textField3.setBounds(220, 390, 190, 30);

        label7.setBackground(new java.awt.Color(204, 204, 204));
        label7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label7.setText("Employee Type");
        getContentPane().add(label7);
        label7.setBounds(80, 500, 96, 19);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(220, 440, 190, 30);

        label8.setBackground(new java.awt.Color(204, 204, 204));
        label8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label8.setText("Email");
        getContentPane().add(label8);
        label8.setBounds(80, 169, 96, 30);

        textField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(textField4);
        textField4.setBounds(220, 170, 190, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 560, 120, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 560, 120, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(320, 560, 120, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Search");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(470, 70, 80, 30);

        label9.setBackground(new java.awt.Color(204, 204, 204));
        label9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label9.setText("Password");
        getContentPane().add(label9);
        label9.setBounds(80, 450, 96, 19);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...select...", "Admin", "Employee" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(220, 490, 140, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Search");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(480, 390, 80, 30);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone", "EmailId", "Username"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(620, 60, 540, 490);

        setBounds(0, 0, 1195, 697);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String url="jdbc:mysql://localhost/eventdb";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{
    
      if(jComboBox1.getSelectedIndex()==0)
    {
        JOptionPane.showMessageDialog(rootPane, "Choose Type");
    }
      else
      {
    String q="insert into addemployee values(?,?,?,?,?,?,?,?)";
    PreparedStatement state=myconn.prepareStatement(q);
    state.setString(1, textField1.getText());
    state.setString(2, textField2.getText());
    state.setString(3, textField4.getText()); 
    state.setString(4, textArea1.getText()); 
    if(jRadioButton1.isSelected())
    {
    state.setString(5,"Female");
    }
    else
    {
    state.setString(5,"Male");
    }
     state.setString(6, textField3.getText());
     state.setString(7, jPasswordField1.getText());
     state.setString(8,jComboBox1.getSelectedItem().toString());
    int res=state.executeUpdate();
    if(res>0)
    {
      JOptionPane.showMessageDialog(rootPane, "Employee Added Succesfully");
       textField1.setText("");
       textField2.setText("");
       textField4.setText("");
       buttonGroup1.clearSelection();
       textArea1.setText("");
       textField3.setText("");
      jPasswordField1.setText("");
    }
    else
    {
           JOptionPane.showMessageDialog(rootPane, "Employee NOT Added Succesfully");
             textField1.setText("");
       textField2.setText("");
       textArea1.setText("");
       jRadioButton1.setName("");
        jRadioButton2.setName("");
       textField3.setText("");
      jPasswordField1.setText("");
       textField4.setText("");
       buttonGroup1.clearSelection();
    }
      }
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String url="jdbc:mysql://localhost/eventdb";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{
      if(jComboBox1.getSelectedIndex()==0)
    {
        JOptionPane.showMessageDialog(rootPane, "Choose Type");
    }
      else
      {
    String q="update addemployee set name=?,phone=?,email=?,address=?,gender=?,password=?,type=?,username=? where username=?";
    PreparedStatement state=myconn.prepareStatement(q);
    state.setString(1, textField1.getText());
    state.setString(2, textField2.getText());
    state.setString(3, textField4.getText()); 
    state.setString(4, textArea1.getText()); 
    if(jRadioButton1.isSelected())
    {
    state.setString(5,"Female");
    }
    else
    {
    state.setString(5,"Male");
    }
     state.setString(6, jPasswordField1.getText());
     
     state.setString(7,jComboBox1.getSelectedItem().toString());
     state.setString(8, textField3.getText());
     state.setString(9, c);
     
     String mid=textField1.getText();
     String mid1=textField2.getText();
     String mid2=textField4.getText();
     String mid3=textField3.getText();
    int res=state.executeUpdate();
   if(res>0)
    {
               DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
               Object myrow[]={mid,mid1,mid2,mid3};
               mymodel.addRow(myrow);
             mymodel.removeRow(d);
     
             JOptionPane.showMessageDialog(rootPane, "Employee Updated Succesfully");
       textField1.setText("");
       textField2.setText("");
       textField4.setText("");
       buttonGroup1.clearSelection();
       textArea1.setText("");
       textField3.setText("");
      jPasswordField1.setText("");
      
    }
   else
   {
             JOptionPane.showMessageDialog(rootPane, "Employee Not Updated Succesfully");
   }
      }
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}
       
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String url="jdbc:mysql://localhost/eventdb";
try
{
    int ch=JOptionPane.showConfirmDialog(rootPane,"Are u Sure to want to delete", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{
    if(ch==JOptionPane.YES_OPTION)
    {
    String q="delete from addemployee where username=?";
    PreparedStatement state=myconn.prepareStatement(q);
    state.setString(1, textField3.getText());

    int res=state.executeUpdate();
   if(res>0)
    {
      JOptionPane.showMessageDialog(rootPane, "Employee Deleted Succesfully");
      textField1.setText("");
       textField2.setText("");
       textField4.setText("");
       buttonGroup1.clearSelection();
       textArea1.setText("");
       textField3.setText("");
      jPasswordField1.setText("");     
      DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
             mymodel.removeRow(d);

    }
   else
   {
             JOptionPane.showMessageDialog(rootPane, "Employee Not Deleted Succesfully");
   }
    }
    else
    {
       textField1.setText("");
       textField2.setText("");
       textField4.setText("");
       buttonGroup1.clearSelection();
       textArea1.setText("");
       textField3.setText("");
      jPasswordField1.setText("");
    }
    
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}
       
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       String url="jdbc:mysql://localhost/eventdb";
       try
       {
           Connection myconn=DriverManager.getConnection(url, "root", "");
           try
           { 
               DefaultTableModel mymodel1=(DefaultTableModel)jTable1.getModel();
               mymodel1.setRowCount(0);

             String q="select * from addemployee where name like'"+textField1.getText()+"%'";
    
            PreparedStatement state=myconn.prepareStatement(q);
           ResultSet res=state.executeQuery();
           while(res.next())
           {
               jButton3.setVisible(true);
               jButton4.setVisible(true);
               String n=res.getString("name");
               String p=res.getString("phone");
               String e=res.getString("email");
               String u=res.getString("username");
      
               DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
               Object myrow[]={n,p,e,u};
               mymodel.addRow(myrow);
               
           }
           if(jTable1.getRowCount()==0)
               {
                   JOptionPane.showMessageDialog(rootPane,"no memebers found");
                   textField1.setText("");
               }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage());
        }
    }
    catch(SQLException e)
    {
       JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                    String url="jdbc:mysql://localhost/eventdb";
       try
       {
           Connection myconn=DriverManager.getConnection(url, "root", "");
           try
           {
                              DefaultTableModel mymodel1=(DefaultTableModel)jTable1.getModel();
               mymodel1.setRowCount(0);

             String q="select * from addemployee where username=?";
             PreparedStatement state=myconn.prepareStatement(q);
             state.setString(1, textField3.getText());
             ResultSet res=state.executeQuery();
             if(res.next())
             {
                 jButton3.setVisible(true);
                 jButton4.setVisible(true);
                 textField1.setText(res.getString("name"));
                 textField2.setText(res.getString("phone"));
                 textField4.setText(res.getString("email"));
                 textArea1.setText(res.getString("address"));
                 textField3.setText(res.getString("username"));
                 jPasswordField1.setText(res.getString("password"));
               
                 if(res.getString("gender").equalsIgnoreCase("Male"))
                 {
                    jRadioButton2.setSelected(true);
                 }
                 else
                 {
                     jRadioButton1.setSelected(true);  
                 }
                 jComboBox1.setSelectedItem(res.getString("type"));
             }
             else
             {
                 JOptionPane.showMessageDialog(rootPane, "Invalid Username"); 
             }
           }
                 catch(Exception e)
                    {
              JOptionPane.showMessageDialog(rootPane, "Error in Query"+e.getMessage());
                    }
       }
       catch(SQLException e)
       {
           JOptionPane.showMessageDialog(rootPane, "Error in Connection"+e.getMessage());
       }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         c=jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
                  String url="jdbc:mysql://localhost/eventdb";
       try
       {
           Connection myconn=DriverManager.getConnection(url, "root", "");
           try
           {
             String q="select * from addemployee where username=?";
             PreparedStatement state=myconn.prepareStatement(q);
             state.setString(1, c);
             ResultSet res=state.executeQuery();
             if(res.next())
             {    d=jTable1.getSelectedRow();
                 textField1.setText(res.getString("name"));
                 textField2.setText(res.getString("phone"));
                 textArea1.setText(res.getString("address"));
                 textField4.setText(res.getString("email"));
                 textField3.setText(res.getString("username"));
                 if(res.getString("gender").equalsIgnoreCase("Male"))
                 {
                    jRadioButton2.setSelected(true);
                 }
                 else
                 {
                     jRadioButton1.setSelected(true);  
                 }
                 jPasswordField1.setText(res.getString("password"));
                 jComboBox1.setSelectedItem(res.getString("type"));
             }
             else
             {
                 JOptionPane.showMessageDialog(rootPane, "Invalid employeeid"); 
             }
           }
                 catch(Exception e)
                    {
              JOptionPane.showMessageDialog(rootPane, "Error in Query"+e.getMessage());
                    }
       }
       catch(SQLException e)
       {
           JOptionPane.showMessageDialog(rootPane, "Error in Connection"+e.getMessage());
       }

    }//GEN-LAST:event_jTable1MouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
jButton3.setVisible(false);      
jButton4.setVisible(false);
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
 jButton2.setBackground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
 jButton2.setBackground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
 jButton3.setBackground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
 jButton3.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
 jButton4.setBackground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
 jButton4.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
 jButton6.setBackground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
 jButton6.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
 jButton5.setBackground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
 jButton5.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    // End of variables declaration//GEN-END:variables
}
