/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package event.management2;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CS
 */
public class addvenue extends javax.swing.JInternalFrame {

    /**
     * Creates new form addvenue
     */
    String c;
    int d;
     JFileChooser fc;
    File myfile;
    String pic = "";

    public addvenue() {
        initComponents();
           Toolkit yk= Toolkit.getDefaultToolkit();
         int x=(int) yk.getScreenSize().getWidth();
         int y=(int) yk.getScreenSize().getHeight();
         this.setSize(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Add Venue");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("VENUE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 0, 182, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Venue Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 50, 144, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 40, 166, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Venue Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 136, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 90, 166, 80);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Venue Image");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 240, 136, 23);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(270, 380, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Venue Capacity");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 420, 136, 23);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(270, 420, 110, 30);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(270, 460, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Prefferd For");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 500, 127, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Venue Cost");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 460, 127, 23);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Marriage", "BirthdayParty", "FarewellParty", "FamilyFunction", "CollegeEvent", "AnniverseryParty", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(270, 500, 160, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 550, 105, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 550, 80, 31);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 550, 86, 31);

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 180, 166, 145);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Upload");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(290, 340, 130, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Venue Phoneno.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 380, 136, 23);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 51, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Phone", "Guests", "Cost"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(560, 40, 560, 510);

        setBounds(0, 0, 1150, 662);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  String url="jdbc:mysql://localhost/eventdb";
try
{
    int ch=JOptionPane.showConfirmDialog(rootPane,"Are u Sure to want to delete", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{
    if(ch==JOptionPane.YES_OPTION)
    {
    String q="delete from addvenues where name=?";
    PreparedStatement state=myconn.prepareStatement(q);
    state.setString(1, c);
    int res=state.executeUpdate();
   if(res>0)
    {
      JOptionPane.showMessageDialog(rootPane, "venue Deleted Succesfully");
       jTextField1.setText("");
       jTextField2.setText("");
       jTextArea1.setText("");
       jTextField3.setText("");
       jTextField4.setText("");  
       jComboBox1.setSelectedIndex(0);jLabel8.setIcon(null);
       DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
             mymodel.removeRow(d);
    }
   else
   {
        JOptionPane.showMessageDialog(rootPane, "wrong phone no. venue not Deleted Succesfully");
       jTextField1.setText("");
       jTextField2.setText("");
       jTextArea1.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
       jComboBox1.setSelectedIndex(0);
       jLabel8.setIcon(null);
   }
    }
    else
    {
        jTextField1.setText("");
       jTextField2.setText("");
       jTextArea1.setText("");
       jTextField3.setText("");
       jTextField4.setText("");  
       jComboBox1.setSelectedIndex(0);
    }
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}
       

       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         String filename="";
                
        if(myfile!=null){
         filename = "image\\"+new Date().getTime() + "_" + myfile.getName();//Date.getTime() added for unique file name.
        int i;
        FileInputStream rd = null;
        FileOutputStream outs = null;
        try {

            rd = new FileInputStream(myfile);
            outs = new FileOutputStream(filename);//writing the new file in 'Images' folder, in the project

            byte[] b = new byte[2048];
            while ((i = rd.read(b)) > 0) {
                outs.write(b, 0, i);

            }
            JOptionPane.showMessageDialog(rootPane, "File saved");
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(rootPane, "error ki hal ne" + e.getMessage());
        } finally
        {
            try {
                rd.close();
                outs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "error in closing file" + e.getMessage());
            }
        }
        }
        else
        {
            filename="image\\default.gif";
        
        }

        String url="jdbc:mysql://localhost/eventdb";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{
      if(jComboBox1.getSelectedIndex()==0)
    {
        JOptionPane.showMessageDialog(rootPane, "Choose Event");
    }
      else
      {
    String q="insert into addvenues values(?,?,?,?,?,?,?)";
    PreparedStatement state=myconn.prepareStatement(q);
    state.setString(1, jTextField1.getText());
    state.setString(2, jTextArea1.getText());
    state.setString(3, jTextField2.getText());
    state.setString(4, jTextField3.getText()); 
    state.setString(5, jTextField4.getText()); 
    state.setString(6, jComboBox1.getSelectedItem().toString());
    state.setString(7, filename);
    String mid=jTextField1.getText();
    String mid1=jTextArea1.getText();
    String mid2=jTextField2.getText();
    String mid3=jTextField3.getText();
    String mid4=jTextField4.getText();
    int res=state.executeUpdate();
    if(res>0)
    {
      JOptionPane.showMessageDialog(rootPane, "Venue Added Succesfully");
      DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
               Object myrow[]={mid,mid1,mid2,mid3,mid4};
               mymodel.addRow(myrow);
       jTextField1.setText("");
       jTextField2.setText("");
       jTextArea1.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
       jLabel8.setText("");
       jComboBox1.setSelectedIndex(0);
     }
    else
    {
           JOptionPane.showMessageDialog(rootPane, "Venue NOT Added Succesfully");
       jTextField1.setText("");
       jTextField2.setText("");
       jTextArea1.setText("");
       jTextField3.setText("");
       jTextField4.setText("");

    }
    
}
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 String filename="";
                
        if(myfile!=null){
         filename = "image\\"+new Date().getTime() + "_" + myfile.getName();//Date.getTime() added for unique file name.
        int i;
        FileInputStream rd = null;
        FileOutputStream outs = null;
        try {

            rd = new FileInputStream(myfile);
            outs = new FileOutputStream(filename);//writing the new file in 'Images' folder, in the project

            byte[] b = new byte[2048];
            while ((i = rd.read(b)) > 0) {
                outs.write(b, 0, i);

            }
            JOptionPane.showMessageDialog(rootPane, "File updated");
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(rootPane, "error ki hal ne" + e.getMessage());
        } finally
        {
            try {
                rd.close();
                outs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "error in closing file" + e.getMessage());
            }
        }
        }
        else
        {
            filename="image\\default.gif";
        
        }
        
        String url="jdbc:mysql://localhost/eventdb";
try
{
    
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{
        if(jComboBox1.getSelectedIndex()==0)
    {
        JOptionPane.showMessageDialog(rootPane, "Choose Event");
    }
        else
        {
    String q="update addvenues set name=?,address=?,phone=?,capacity=?,cost=?,events=?,image=? where name=?";
    PreparedStatement state=myconn.prepareStatement(q);
    
    state.setString(1, jTextField1.getText());
    state.setString(2, jTextArea1.getText());
    state.setString(3, jTextField2.getText()); 
    state.setString(4, jTextField3.getText()); 
    state.setString(5, jTextField4.getText()); 
 
     state.setString(6,jComboBox1.getSelectedItem().toString()); 
     state.setString(7, filename);
     state.setString(8, c);
    int res=state.executeUpdate();
    String mid=jTextField1.getText();
    String mid1=jTextArea1.getText();
    String mid2=jTextField2.getText();
    String mid3=jTextField3.getText();
    String mid4=jTextField4.getText();
   if(res>0)
    {
      JOptionPane.showMessageDialog(rootPane, "Venue Updated Succesfully");      
               DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
               Object myrow[]={mid,mid1,mid2,mid3,mid4};
               mymodel.addRow(myrow);
             mymodel.removeRow(d);
       jTextField1.setText("");
       jTextField2.setText("");
       jTextArea1.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
       jComboBox1.setSelectedIndex(0);
       jLabel8.setText("");
    }
   else
   {
       JOptionPane.showMessageDialog(rootPane, "wrong name  Venue not Updated Succesfully");
    
   }
   }
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 fc = new JFileChooser();

        fc.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                }
                int pos = f.getName().lastIndexOf('.');
                if (pos == -1) {
                    return false;
                } else {
                    String extention = f.getName().substring(pos + 1);//saving the extension
                    String str[] = {"gif", "png", "jpg", "jpeg"};//allowed extentions
                    for (String allwd : str) {

                        if (extention.equalsIgnoreCase(allwd)) {
                            return true;
                        }
                    }
                    return false;
                }

            }

            @Override
            public String getDescription() {

                return "image files";
            }
        });
        int result = fc.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            myfile = fc.getSelectedFile();

            try {
                jLabel8.setIcon(new ImageIcon(ImageIO.read(myfile)));
            } catch (IOException e) {
                JOptionPane.showMessageDialog(rootPane, "Error");
                e.printStackTrace();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
 jButton5.setBackground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
 jButton5.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseExited

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    try
    {
        String url="jdbc:mysql://localhost/eventdb";
        Connection myconn=DriverManager.getConnection(url, "root", "");
        try
        {
            jButton1.setVisible(false);
            jButton3.setVisible(false);
            String q="select * from addvenues";
            
            PreparedStatement state=myconn.prepareStatement(q);
       
            ResultSet res=state.executeQuery();
           while(res.next())
           {
               String mid=res.getString("name");
               String bid=res.getString("address");
               String type=res.getString("phone");
               String place=res.getString("capacity");
               String g=res.getString("cost");
               DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
               Object myrow[]={mid,bid,type,place,g};
               mymodel.addRow(myrow);
              
           }
            if(jTable1.getRowCount()==0)
               {
                   JOptionPane.showMessageDialog(rootPane,"no venues found");
               }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage());
        }
    }
    catch(SQLException e)
    {
       JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         c=jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                  String url="jdbc:mysql://localhost/eventdb";
       try
       {
           Connection myconn=DriverManager.getConnection(url, "root", "");
           try
           {
             String q="select * from addvenues where name=?";
             PreparedStatement state=myconn.prepareStatement(q);
             state.setString(1, c);
             ResultSet res=state.executeQuery();
             if(res.next())
             {
                 jButton1.setVisible(true);
                  jButton3.setVisible(true);
            
                  d=jTable1.getSelectedRow();
                 jTextField1.setText(res.getString("name"));
                 jTextField2.setText(res.getString("phone"));
                 jTextArea1.setText(res.getString("address"));
                 jTextField3.setText(res.getString("capacity"));
                 jTextField4.setText(res.getString("cost"));
               jComboBox1.setSelectedItem(res.getString("events"));
                   String ofile=(res.getString("image"));
                   ofile=res.getString("image");
Image simg = ImageIO.read( new File(ofile)).getScaledInstance( jLabel8.getWidth(), jLabel8.getHeight(), Image.SCALE_DEFAULT);
 jLabel8.setIcon(new ImageIcon(simg)); 
                 
             }
             else
             {
                 JOptionPane.showMessageDialog(rootPane, "Invalid venue name"); 
             }
           }
                 catch(Exception e)
                    {
              JOptionPane.showMessageDialog(rootPane, "Error in Query"+e.getMessage());
                    }
       }
       catch(SQLException e)
       {
           JOptionPane.showMessageDialog(rootPane, "Error in Connection"+e.getMessage());
       }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
