/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package event.management2;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author CS
 */
public class bookingeq extends javax.swing.JInternalFrame
{
public String bookingid;
public int d=0;
/**
     * Creates new form booking
     */
    public bookingeq() {
        initComponents();
           Toolkit yk= Toolkit.getDefaultToolkit();
         int x=(int) yk.getScreenSize().getWidth();
         int y=(int) yk.getScreenSize().getHeight();
         jLabel10.setSize(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Booking Events");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FOR NEW BOOKINGS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 110, 300, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("MemberID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 170, 128, 34);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(280, 170, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("BookingID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 220, 128, 34);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(280, 220, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Event Type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 270, 128, 50);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 280, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Event Place");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 330, 128, 50);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose" }));
        jComboBox2.setMinimumSize(new java.awt.Dimension(131, 21));
        jComboBox2.setPreferredSize(new java.awt.Dimension(131, 21));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(280, 340, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Guests");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 390, 128, 50);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(280, 400, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Date");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 450, 128, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Equipments");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(620, 170, 140, 30);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(102, 0, 0));
        jCheckBox1.setText("Mikes&Speakers");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jCheckBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBox1KeyPressed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(620, 220, 130, 23);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(102, 0, 0));
        jCheckBox2.setText("Stage");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jCheckBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBox2KeyPressed(evt);
            }
        });
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(760, 220, 100, 23);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(102, 0, 0));
        jCheckBox3.setText("DJ");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jCheckBox3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBox3KeyPressed(evt);
            }
        });
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(550, 220, 50, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 510, 100, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 0, 0));
        jButton3.setText("Next");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton3KeyReleased(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(610, 270, 61, 23);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 0, 0);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(280, 460, 150, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\CS\\Desktop\\download (1).png")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1028, 589);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed

    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
       String url="jdbc:mysql://localhost/eventdb";
        try
        {
            Connection myconn=DriverManager.getConnection(url, "root", "");
            try
            { 
    String q1="select * from addvenues";
    PreparedStatement state2=myconn.prepareStatement(q1);
    ResultSet res2=state2.executeQuery();
 
while(res2.next())
{
    jComboBox2.addItem(res2.getString("name"));
}
if(jComboBox2.getItemCount()==1)
{
    jComboBox2.removeAllItems();
    jComboBox2.addItem("no venue");
}
     String q2="select * from addevent";
    PreparedStatement state3=myconn.prepareStatement(q2);
    ResultSet res3=state3.executeQuery();
while(res3.next())
{
    jComboBox1.addItem(res3.getString("name"));
}
if(jComboBox1.getItemCount()==1)
{
    jComboBox1.removeAllItems();
    jComboBox1.addItem("no event");
}             
                String q="select * from booking where bookingid=?";
                PreparedStatement state=myconn.prepareStatement(q);
                state.setString(1, bookingid);

                ResultSet res=state.executeQuery();
                if(res.next())
                {
                    jTextField1.setText(res.getString("memberid"));
                    jTextField2.setText(bookingid);
                    jTextField3.setText(res.getString("guests"));
                    jDateChooser1.setDate(res.getDate("date"));
                    jComboBox1.setSelectedItem(res.getString("type"));
                    jComboBox2.setSelectedItem(res.getString("place"));
                    String eq2=res.getString("equipments");
                    if(eq2.equalsIgnoreCase("dj"))
                    {
                        jCheckBox3.setSelected(true);
                    }
                    else if(eq2.equalsIgnoreCase("mike&speaker"))
                    {
                        jCheckBox1.setSelected(true);
                    }
                    else if(eq2.equalsIgnoreCase("stage"))
                    { 
                        jCheckBox2.setSelected(true);
                    }
                    else if(eq2.equalsIgnoreCase("dj,mike&speaker"))
                    {  
                        jCheckBox3.setSelected(true);
                        jCheckBox1.setSelected(true);
                    }
                    else if(eq2.equalsIgnoreCase("dj,stage"))
                    {
                        jCheckBox3.setSelected(true);
                        jCheckBox2.setSelected(true);
                    } 
                    else if(eq2.equalsIgnoreCase("mike&speaker,stage"))
                    {
                        jCheckBox1.setSelected(true);
                        jCheckBox2.setSelected(true);
                    }
                    else if(eq2.equalsIgnoreCase("dj,mike&speaker,stage"))
                    {
                        jCheckBox1.setSelected(true);
                        jCheckBox3.setSelected(true);
                        jCheckBox2.setSelected(true);
                    }
                    else
                    {
                        
                    } 
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Invalid Booking Id");
                    jTextField2.setText("");
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error in Query"+e.getMessage());
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection"+e.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   booking1 obj = new booking1();
       obj.bookingid=jTextField2.getText();
       obj.d=2;
        mainform.jDesktopPane2.add(obj);
        obj.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(jComboBox1.getSelectedIndex()==0||jComboBox2.getSelectedIndex()==0)
{
    if(jComboBox1.getSelectedIndex()==0)
    JOptionPane.showMessageDialog(rootPane,"First Add Event");
    else
    JOptionPane.showMessageDialog(rootPane,"First Add Venues");
}

 else if(d==2)
     {
        String url="jdbc:mysql://localhost/eventdb";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{
 Date f=jDateChooser1.getDate();
   Date cur=new Date();
     if(jComboBox1.getSelectedIndex()==0 || jComboBox2.getSelectedIndex()==0  || (f.compareTo(cur)<0) || jDateChooser1.getDate()==(null)||jTextField1.getText().equalsIgnoreCase("")||jTextField3.getText().equalsIgnoreCase(""))
    {
        if(jDateChooser1.getDate()==null)
        {
JOptionPane.showMessageDialog(rootPane, "Choose Date");
        }
        else if((f.compareTo(cur)<0)) 
    {
JOptionPane.showMessageDialog(rootPane, "Date is wrong");
    }
        else
        {        
JOptionPane.showMessageDialog(rootPane, "Please fill full info..");
        }
    }
        else
       {             String o="select * from addmember where memberid=?";
             PreparedStatement state1=myconn.prepareStatement(o);
             state1.setString(1, jTextField1.getText());
             ResultSet res1=state1.executeQuery();

             if(res1.next())
             {


    String q="update booking set memberid=?,type=?,place=?,guests=?,date=?,equipments=? where bookingid=?";
    PreparedStatement state=myconn.prepareStatement(q);
    state.setString(1, jTextField1.getText());   
    state.setString(2, jComboBox1.getSelectedItem().toString());
    state.setString(3, jComboBox2.getSelectedItem().toString());
    state.setString(4, jTextField3.getText()); 
    
    SimpleDateFormat mydate=new SimpleDateFormat("yyyy-MM-dd");
    String ob=mydate.format(jDateChooser1.getDate());
    state.setString(5, ob);
    String eq="";
if(jCheckBox3.isSelected())
{
    eq=eq+"dj,";
}
if(jCheckBox1.isSelected())
{
     eq=eq+"mike&speaker,";
}
if(jCheckBox2.isSelected())
{
     eq=eq+"stage,";
}
if(eq.length()>1)
eq=eq.substring(0, eq.length()-1);
else
    eq=eq;
state.setString(6,eq);

    state.setString(7, jTextField2.getText()); 
   
    String r2="select date from booking where date =?";
    PreparedStatement state3=myconn.prepareStatement(r2);
    SimpleDateFormat mydate7=new SimpleDateFormat("yyyy-MM-dd");
    String ob7=mydate7.format(jDateChooser1.getDate());
    state3.setString(1, ob7); 
    ResultSet res3=state3.executeQuery();
    String h;
    if(res3.next())
    {      
   String p=jComboBox2.getSelectedItem().toString();
   int k=Integer.parseInt(jTextField2.getText());
   String st1="";
   String r3="select * from booking where date=?";
   PreparedStatement state9=myconn.prepareStatement(r3);
   state9.setString(1,ob7);
   ResultSet res8=state9.executeQuery();
   while(res8.next())
   {
     if(k!=res8.getInt("bookingid"))
     {
        st1=st1+res8.getString("place");
     }
   } 
   if(st1.toLowerCase().contains(p))
   {  
     JOptionPane.showMessageDialog(rootPane, "**Please Change Venue OR Date**");  
   }
   else
   {
int res=state.executeUpdate();
if(res>0)
{
          JOptionPane.showMessageDialog(rootPane, "Bookings Updated Succesfully"); 
        bookingfood obj = new bookingfood();
        obj.bookingid=jTextField2.getText();
        mainform.jDesktopPane2.add(obj);
        obj.setVisible(true);
        this.dispose();
}      
else
   {
       JOptionPane.showMessageDialog(rootPane, "Booking not Updated Succesfully");
     //JOptionPane.showMessageDialog(rootPane, "Member not updated Succesfully date hi nhi si database vich");  
   }  
   }
    }
    
    
    else
    {
       int res=state.executeUpdate();
   if(res>0)
    { 
     // JOptionPane.showMessageDialog(rootPane, "Member  Updated Succesfully date hi nhi si database vich");
      JOptionPane.showMessageDialog(rootPane, "Booking Updated Succesfully");
          bookingfood obj = new bookingfood();
          obj.bookingid=jTextField2.getText();
          mainform.jDesktopPane2.add(obj);
          obj.setVisible(true);
         // this.dispose();
    }
       else
   {
       JOptionPane.showMessageDialog(rootPane, "Booking not Updated Succesfully");
     //JOptionPane.showMessageDialog(rootPane, "Member not updated Succesfully date hi nhi si database vich");  
   }  
    }
             }
             else
             {
       JOptionPane.showMessageDialog(rootPane, "member id is wrong");
             }
       
       }
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}
     }
     else
     {
         String url="jdbc:mysql://localhost/eventdb";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{
 Date f=jDateChooser1.getDate();
   Date cur=new Date();
     if(jComboBox1.getSelectedIndex()==0 || jComboBox2.getSelectedIndex()==0  || (f.compareTo(cur)<0) || jDateChooser1.getDate()==(null)||jTextField1.getText().equalsIgnoreCase("")||jTextField3.getText().equalsIgnoreCase(""))
    {
        if(jDateChooser1.getDate()==null)
        {
JOptionPane.showMessageDialog(rootPane, "Choose Date");
        }
        else if((f.compareTo(cur)<0)) 
    {
JOptionPane.showMessageDialog(rootPane, "Date is wrong");
    }
        else
        {        
JOptionPane.showMessageDialog(rootPane, "Please fill full info..");
        }
    }
        else
       {
    String q="update booking set memberid=?,type=?,place=?,guests=?,date=?,equipments=? where bookingid=?";
    PreparedStatement state=myconn.prepareStatement(q);
    state.setString(1, jTextField1.getText());   
    state.setString(2, jComboBox1.getSelectedItem().toString());
    state.setString(3, jComboBox2.getSelectedItem().toString());
    state.setString(4, jTextField3.getText()); 
    
    SimpleDateFormat mydate=new SimpleDateFormat("yyyy-MM-dd");
    String ob=mydate.format(jDateChooser1.getDate());
    state.setString(5, ob);
    String eq="";
if(jCheckBox3.isSelected())
{
    eq=eq+"dj,";
}
if(jCheckBox1.isSelected())
{
     eq=eq+"mike&speaker,";
}
if(jCheckBox2.isSelected())
{
     eq=eq+"stage,";
}
if(eq.length()>1)
eq=eq.substring(0, eq.length()-1);
else
    eq=eq;
state.setString(6,eq);

    state.setString(7, jTextField2.getText()); 
   
    String r2="select date from booking where date =?";
    PreparedStatement state3=myconn.prepareStatement(r2);
    SimpleDateFormat mydate7=new SimpleDateFormat("yyyy-MM-dd");
    String ob7=mydate7.format(jDateChooser1.getDate());
    state3.setString(1, ob7); 
    ResultSet res3=state3.executeQuery();
    String h;
    if(res3.next())
    {      
   String p=jComboBox2.getSelectedItem().toString();
   int k=Integer.parseInt(jTextField2.getText());
   String st1="";
   String r3="select * from booking where date=?";
   PreparedStatement state9=myconn.prepareStatement(r3);
   state9.setString(1,ob7);
   ResultSet res8=state9.executeQuery();
   while(res8.next())
   {
     if(k!=res8.getInt("bookingid"))
     {
        st1=st1+res8.getString("place");
     }
   } 
   if(st1.toLowerCase().contains(p))
   {  
     JOptionPane.showMessageDialog(rootPane, "**Please Change Venue OR Date**");  
   }
   else
   {
int res=state.executeUpdate();
if(res>0)
{
          JOptionPane.showMessageDialog(rootPane, "Bookings added Succesfully"); 
        bookingfood obj = new bookingfood();
        obj.bookingid=jTextField2.getText();
        mainform.jDesktopPane2.add(obj);
        obj.setVisible(true);
        this.dispose();
}      
else
   {
       JOptionPane.showMessageDialog(rootPane, "Booking not added Succesfully");
     //JOptionPane.showMessageDialog(rootPane, "Member not updated Succesfully date hi nhi si database vich");  
   }  
   }
    }
    
    
    else
    {
       int res=state.executeUpdate();
   if(res>0)
    { 
     // JOptionPane.showMessageDialog(rootPane, "Member  Updated Succesfully date hi nhi si database vich");
      JOptionPane.showMessageDialog(rootPane, "Booking added Succesfully");
          bookingfood obj = new bookingfood();
          obj.bookingid=jTextField2.getText();
          mainform.jDesktopPane2.add(obj);
          obj.setVisible(true);
         // this.dispose();
    }
       else
   {
       JOptionPane.showMessageDialog(rootPane, "Booking not added Succesfully");
     //JOptionPane.showMessageDialog(rootPane, "Member not updated Succesfully date hi nhi si database vich");  
   }  
    }
      
       
       }
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}   
     }
     



    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
   
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
jButton3.setBackground(Color.GRAY);   
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
jButton3.setBackground(Color.LIGHT_GRAY);         //jButton3.setBackground(Color.WHITE);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
 
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3KeyReleased

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
jButton2.setBackground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
jButton2.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseExited

    private void jCheckBox3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox3KeyPressed
    
    }//GEN-LAST:event_jCheckBox3KeyPressed

    private void jCheckBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox1KeyPressed
    
    }//GEN-LAST:event_jCheckBox1KeyPressed

    private void jCheckBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox2KeyPressed
        
    }//GEN-LAST:event_jCheckBox2KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables


}