/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package event.management2;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author CS
 */
public class bookingfood extends javax.swing.JInternalFrame {
public String bookingid;
public int g=0;
int l=0,d=0,t=0,b=0;   /**
     * Creates new form booking
     */
    public bookingfood() {
        initComponents();
           Toolkit yk= Toolkit.getDefaultToolkit();
         int x=(int) yk.getScreenSize().getWidth();
         int y=(int) yk.getScreenSize().getHeight();
        jLabel7.setSize(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Booking Events");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("FOR BOOKING");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 20, 226, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("MemberID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 90, 128, 34);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 51, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(280, 90, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("BookingID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 140, 128, 34);

        jTextField2.setBackground(new java.awt.Color(240, 240, 240));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(280, 140, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Event Type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 190, 128, 50);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 51, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 200, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Event Place");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 250, 128, 50);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(102, 51, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(280, 260, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("Guests");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 310, 128, 50);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(280, 320, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 51, 0));
        jLabel9.setText("Date");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 370, 128, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 0));
        jButton1.setText("Next");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(720, 450, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Food");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(660, 70, 140, 30);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(102, 51, 0));
        jCheckBox1.setText("Lunch");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(540, 210, 80, 23);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(102, 51, 0));
        jCheckBox2.setText("Dinner");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(540, 280, 100, 23);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(102, 51, 0));
        jCheckBox3.setText("Breakfast");
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox3ItemStateChanged(evt);
            }
        });
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(540, 140, 100, 30);

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(102, 51, 0));
        jCheckBox4.setText("Tea&Snacks");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(540, 340, 100, 23);

        jComboBox3.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(102, 51, 0));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Dinner Type", "Normaldinner", "Deluxdinner", "Royaldinner" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(710, 280, 200, 30);

        jComboBox6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox6.setForeground(new java.awt.Color(102, 51, 0));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Lunch Type", "Normallunch", "Deluxlunch", "Royallunch" }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(710, 210, 200, 30);

        jComboBox7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox7.setForeground(new java.awt.Color(102, 51, 0));
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Breakfast Type", "Normalbreakfast", "Deluxbreakfast", "Royalbreakfast" }));
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(710, 140, 200, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 51, 0));
        jButton2.setText("BACK");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 453, 80, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(280, 380, 150, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\CS\\Desktop\\download (1).png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1028, 615);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(jComboBox1.getSelectedIndex()==0||jComboBox2.getSelectedIndex()==0)
{
    if(jComboBox1.getSelectedIndex()==0)
    JOptionPane.showMessageDialog(rootPane,"First Add Event");
    else
    JOptionPane.showMessageDialog(rootPane,"First Add Venues");
}
else if(g==2)
{
    
     String url="jdbc:mysql://localhost/eventdb";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{
 Date f=jDateChooser1.getDate();
   Date cur=new Date();
     if(jComboBox1.getSelectedIndex()==0 || jComboBox2.getSelectedIndex()==0  || (f.compareTo(cur)<0) || jDateChooser1.getDate()==(null)|| jTextField2.getText().equalsIgnoreCase("") ||jTextField1.getText().equalsIgnoreCase("")||jTextField3.getText().equalsIgnoreCase(""))
    {
        if(jDateChooser1.getDate()==null)
        {
JOptionPane.showMessageDialog(rootPane, "Choose Date");
        }
        else if((f.compareTo(cur)<0)) 
    {
JOptionPane.showMessageDialog(rootPane, "Date is wrong");
    }
        else
        {     
JOptionPane.showMessageDialog(rootPane, "Please fill full info..");
        }
    }
        else
       {
                      String o="select * from addmember where memberid=?";
             PreparedStatement state1=myconn.prepareStatement(o);
             state1.setString(1, jTextField1.getText());
             ResultSet res1=state1.executeQuery();

             if(res1.next())
             {

    String q="update booking set memberid=?,type=?,place=?,guests=?,date=?,breakfast=?,lunch=?,tea=?,dinner=? where bookingid=?";
    PreparedStatement state=myconn.prepareStatement(q);
    state.setString(1, jTextField1.getText());   
    state.setString(2, jComboBox1.getSelectedItem().toString());
    state.setString(3, jComboBox2.getSelectedItem().toString());
    state.setString(4, jTextField3.getText()); 
  
    SimpleDateFormat mydate=new SimpleDateFormat("yyyy-MM-dd");
    String ob=mydate.format(jDateChooser1.getDate());
    state.setString(5, ob); 
 
if(jCheckBox3.isSelected())
{
    if(jComboBox7.getSelectedIndex()==0)
    {
      JOptionPane.showMessageDialog(rootPane, "first choose breakfast type");  
    }
   else
    {
        b=1;
        state.setString(6,jComboBox7.getSelectedItem().toString());
    }
}
else
{
      b=1;
     state.setString(6,"no");
}
if(jCheckBox1.isSelected())
{
    if(jComboBox6.getSelectedIndex()==0)
    {
      JOptionPane.showMessageDialog(rootPane, "first choose lunch type");   
    }
   else
    {
        l=1;
        state.setString(7,jComboBox6.getSelectedItem().toString());
    }
}
else
{
     l=1;
     state.setString(7,"no");
}
if(jCheckBox4.isSelected())
{
    state.setString(8,"yes");
}
else
{
     state.setString(8,"no");
}
if(jCheckBox2.isSelected())
{
    if(jComboBox3.getSelectedIndex()==0)
    {
      JOptionPane.showMessageDialog(rootPane, "first choose dinner type"); 
    }
   else
    {
        d=1;
        state.setString(9,jComboBox3.getSelectedItem().toString());
    }
}
else
{
    d=1;
     state.setString(9,"no");
}

    state.setString(10, jTextField2.getText()); 
   
    String r2="select date from booking where date =?";
    PreparedStatement state3=myconn.prepareStatement(r2);
    SimpleDateFormat mydate7=new SimpleDateFormat("yyyy-MM-dd");
    String ob7=mydate7.format(jDateChooser1.getDate());
    state3.setString(1, ob7); 
    ResultSet res3=state3.executeQuery();
    String h;
    if(res3.next())
    { 
        
    String p=jComboBox2.getSelectedItem().toString();
   int k=Integer.parseInt(jTextField2.getText());
   String st1="";
   String r3="select * from booking where date=?";
   PreparedStatement state9=myconn.prepareStatement(r3);
   state9.setString(1,ob7);
   ResultSet res8=state9.executeQuery();
   while(res8.next())
   {
     if(k!=res8.getInt("bookingid"))
     {
        st1=st1+res8.getString("place");
     }
   } 
   if(st1.toLowerCase().contains(p))
   {  
     JOptionPane.showMessageDialog(rootPane, "**Please Change Venue OR Date**");  
   }
   else
   {
       int res;
       if(l==1 && b==1 && d==1)
       {
 res=state.executeUpdate();
       }
       else
       {
  res=0;
  t=1;
       }
if(res>0)
{
          JOptionPane.showMessageDialog(rootPane, "Booking updated Succesfully");
          bookingdeco obj = new bookingdeco();
          obj.bookingid=jTextField2.getText();
          mainform.jDesktopPane2.add(obj);
          obj.setVisible(true);
          this.dispose();  
}
else
{
    if(t==0)
       JOptionPane.showMessageDialog(rootPane, "Booking not updated Succesfully");
}
   }
    }
    
    
    else
    {
       int res;  
       if(l==1 && b==1 && d==1)
       {
 res=state.executeUpdate();
       }
       else
       {
  res=0;
  t=1;
       }
   if(res>0)
    { 
     // JOptionPane.showMessageDialog(rootPane, "Member  Updated Succesfully date hi nhi si database vich");
      JOptionPane.showMessageDialog(rootPane, "Booking updated Succesfully");
          bookingdeco obj = new bookingdeco();
          obj.bookingid=jTextField2.getText();
          mainform.jDesktopPane2.add(obj);
          obj.setVisible(true);
          this.dispose();
    }
      else
   {  
       if(t==0)
       JOptionPane.showMessageDialog(rootPane, "error");
     //JOptionPane.showMessageDialog(rootPane, "Member not updated Succesfully date hi nhi si database vich");  
   }   
    }
      
             }
             else
             {
                  JOptionPane.showMessageDialog(rootPane, "member id not available");
             }
       }
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}

}

else
{
    
     String url="jdbc:mysql://localhost/eventdb";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{
 Date f=jDateChooser1.getDate();
   Date cur=new Date();
     if(jComboBox1.getSelectedIndex()==0 || jComboBox2.getSelectedIndex()==0  || (f.compareTo(cur)<0) || jDateChooser1.getDate()==(null)|| jTextField2.getText().equalsIgnoreCase("") ||jTextField1.getText().equalsIgnoreCase("")||jTextField3.getText().equalsIgnoreCase(""))
    {
        if(jDateChooser1.getDate()==null)
        {
JOptionPane.showMessageDialog(rootPane, "Choose Date");
        }
        else if((f.compareTo(cur)<0)) 
    {
JOptionPane.showMessageDialog(rootPane, "Date is wrong");
    }
        else
        {     
JOptionPane.showMessageDialog(rootPane, "Please fill full info..");
        }
    }
        else
       {
    String q="update booking set memberid=?,type=?,place=?,guests=?,date=?,breakfast=?,lunch=?,tea=?,dinner=? where bookingid=?";
    PreparedStatement state=myconn.prepareStatement(q);
    state.setString(1, jTextField1.getText());   
    state.setString(2, jComboBox1.getSelectedItem().toString());
    state.setString(3, jComboBox2.getSelectedItem().toString());
    state.setString(4, jTextField3.getText()); 
  
    SimpleDateFormat mydate=new SimpleDateFormat("yyyy-MM-dd");
    String ob=mydate.format(jDateChooser1.getDate());
    state.setString(5, ob); 
 
if(jCheckBox3.isSelected())
{
    if(jComboBox7.getSelectedIndex()==0)
    {
      JOptionPane.showMessageDialog(rootPane, "first choose breakfast type");  
    }
   else
    {
        b=1;
        state.setString(6,jComboBox7.getSelectedItem().toString());
    }
}
else
{
      b=1;
     state.setString(6,"no");
}
if(jCheckBox1.isSelected())
{
    if(jComboBox6.getSelectedIndex()==0)
    {
      JOptionPane.showMessageDialog(rootPane, "first choose lunch type");   
    }
   else
    {
        l=1;
        state.setString(7,jComboBox6.getSelectedItem().toString());
    }
}
else
{
     l=1;
     state.setString(7,"no");
}
if(jCheckBox4.isSelected())
{
    state.setString(8,"yes");
}
else
{
     state.setString(8,"no");
}
if(jCheckBox2.isSelected())
{
    if(jComboBox3.getSelectedIndex()==0)
    {
      JOptionPane.showMessageDialog(rootPane, "first choose dinner type"); 
    }
   else
    {
        d=1;
        state.setString(9,jComboBox3.getSelectedItem().toString());
    }
}
else
{
    d=1;
     state.setString(9,"no");
}

    state.setString(10, jTextField2.getText()); 
   
    String r2="select date from booking where date =?";
    PreparedStatement state3=myconn.prepareStatement(r2);
    SimpleDateFormat mydate7=new SimpleDateFormat("yyyy-MM-dd");
    String ob7=mydate7.format(jDateChooser1.getDate());
    state3.setString(1, ob7); 
    ResultSet res3=state3.executeQuery();
    String h;
    if(res3.next())
    { 
        
    String p=jComboBox2.getSelectedItem().toString();
   int k=Integer.parseInt(jTextField2.getText());
   String st1="";
   String r3="select * from booking where date=?";
   PreparedStatement state9=myconn.prepareStatement(r3);
   state9.setString(1,ob7);
   ResultSet res8=state9.executeQuery();
   while(res8.next())
   {
     if(k!=res8.getInt("bookingid"))
     {
        st1=st1+res8.getString("place");
     }
   } 
   if(st1.toLowerCase().contains(p))
   {  
     JOptionPane.showMessageDialog(rootPane, "**Please Change Venue OR Date**");  
   }
   else
   {
       int res;
       if(l==1 && b==1 && d==1)
       {
 res=state.executeUpdate();
       }
       else
       {
  res=0;
  t=1;
       }
if(res>0)
{
          JOptionPane.showMessageDialog(rootPane, "Booking added Succesfully");
          bookingdeco obj = new bookingdeco();
          obj.bookingid=jTextField2.getText();
          mainform.jDesktopPane2.add(obj);
          obj.setVisible(true);
          this.dispose();  
}
else
{
    if(t==0)
       JOptionPane.showMessageDialog(rootPane, "Booking not added Succesfully");
}
   }
    }
    
    
    else
    {
       int res;  
       if(l==1 && b==1 && d==1)
       {
 res=state.executeUpdate();
       }
       else
       {
  res=0;
  t=1;
       }
   if(res>0)
    { 
     // JOptionPane.showMessageDialog(rootPane, "Member  Updated Succesfully date hi nhi si database vich");
      JOptionPane.showMessageDialog(rootPane, "Booking added Succesfully");
          bookingdeco obj = new bookingdeco();
          obj.bookingid=jTextField2.getText();
          mainform.jDesktopPane2.add(obj);
          obj.setVisible(true);
          this.dispose();
    }
      else
   {  
       if(t==0)
       JOptionPane.showMessageDialog(rootPane, "error");
     //JOptionPane.showMessageDialog(rootPane, "Member not updated Succesfully date hi nhi si database vich");  
   }   
    }
      
       
       }
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}

}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

        jComboBox7.setVisible(false);
        jComboBox6.setVisible(false);
        jComboBox3.setVisible(false);
        String url="jdbc:mysql://localhost/eventdb";
       try
       {
           Connection myconn=DriverManager.getConnection(url, "root", "");
           try
           {
                
    String q1="select * from addvenues";
    PreparedStatement state2=myconn.prepareStatement(q1);
    ResultSet res2=state2.executeQuery();
 
while(res2.next())
{
    jComboBox2.addItem(res2.getString("name"));
}
if(jComboBox2.getItemCount()==1)
{
    jComboBox2.removeAllItems();
    jComboBox2.addItem("no venue");
}
  String q2="select * from addevent";
    PreparedStatement state3=myconn.prepareStatement(q2);
    ResultSet res3=state3.executeQuery();
while(res3.next())
{
    jComboBox1.addItem(res3.getString("name"));
}
if(jComboBox1.getItemCount()==1)
{
    jComboBox1.removeAllItems();
    jComboBox1.addItem("no event");
}

             String q="select * from booking where bookingid=?";
             PreparedStatement state=myconn.prepareStatement(q);
             state.setString(1, bookingid);
             ResultSet res=state.executeQuery();
             if(res.next())
             {
                 jTextField1.setText(res.getString("memberid"));
                 jTextField2.setText(res.getString("bookingid"));
                 jTextField3.setText(res.getString("guests"));
                 jDateChooser1.setDate(res.getDate("date"));
                 jComboBox1.setSelectedItem(res.getString("type")); 
                 jComboBox2.setSelectedItem(res.getString("place")); 
                 
                 if(res.getString("breakfast").equalsIgnoreCase("") && res.getString("lunch").equalsIgnoreCase("") && res.getString("tea").equalsIgnoreCase("") && res.getString("dinner").equalsIgnoreCase(""))
                 {             
                     jComboBox7.setVisible(false);
                     jComboBox6.setVisible(false);
                     jComboBox3.setVisible(false);
                     jCheckBox1.setSelected(false);
                     jCheckBox2.setSelected(false);
                     jCheckBox3.setSelected(false);
                     jCheckBox4.setSelected(false);  
                 }
                 if(res.getString("breakfast").equalsIgnoreCase("no") )
                 { 
                   jCheckBox3.setSelected(false);
                   jComboBox7.setVisible(false);  
                 }
                 else if(!res.getString("breakfast").equalsIgnoreCase(""))
                 {
                   jCheckBox3.setSelected(true);
                   jComboBox7.setVisible(true);
                   jComboBox7.setSelectedItem(res.getString("breakfast")); 
                 }
                 if(res.getString("lunch").equalsIgnoreCase("no"))
                 {
                   jCheckBox1.setSelected(false);
                   jComboBox6.setVisible(false);
                 }
                 else if(!res.getString("lunch").equalsIgnoreCase(""))
                 {
                   jCheckBox1.setSelected(true);
                   jComboBox6.setVisible(true);
                   jComboBox6.setSelectedItem(res.getString("lunch"));  
                
                 }
                 if(res.getString("dinner").equalsIgnoreCase("no"))
                 {   jCheckBox2.setSelected(false);
                   jComboBox3.setVisible(false);
                 }
                 else if(!res.getString("dinner").equalsIgnoreCase(""))
                 {
                   jCheckBox2.setSelected(true);
                   jComboBox3.setVisible(true);
                   jComboBox3.setSelectedItem(res.getString("dinner"));
                  
                 }
                 
                 if(res.getString("tea").equalsIgnoreCase("yes"))
                 {
                     jCheckBox4.setSelected(true);
                 }
                 else if(!res.getString("tea").equalsIgnoreCase(""))
                 {
                      jCheckBox4.setSelected(false);  
                 }
             }
             else
             {
                 JOptionPane.showMessageDialog(rootPane, "Invalid Booking Id"); 
                 jTextField2.setText("");
             }
           }
                 catch(Exception e)
                    {
              JOptionPane.showMessageDialog(rootPane, "Error in Query"+e.getMessage());
                    }
       }
       catch(SQLException e)
       {
           JOptionPane.showMessageDialog(rootPane, "Error in Connection"+e.getMessage());
       }       
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
jButton1.setBackground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
jButton1.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
jButton2.setBackground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
jButton2.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseExited

    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
if(jCheckBox3.isSelected())
{
    jComboBox7.setVisible(true);
}
else
{
    jComboBox7.setVisible(false);
}
    }//GEN-LAST:event_jCheckBox3ItemStateChanged

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
  if(jCheckBox1.isSelected())
{
    jComboBox6.setVisible(true);
}
else
{
    jComboBox6.setVisible(false);
}      // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
if(jCheckBox2.isSelected())
{
    jComboBox3.setVisible(true);
}
else
{
    jComboBox3.setVisible(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 bookingeq obj = new bookingeq();
       obj.bookingid=jTextField2.getText();
       obj.d=2;
        mainform.jDesktopPane2.add(obj);
        obj.setVisible(true);
       this.dispose();       
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
