/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package event.management2;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author CS
 */
public class Cost extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cost
     */
    public Cost() {
        initComponents();
           Toolkit yk= Toolkit.getDefaultToolkit();
         int x=(int) yk.getScreenSize().getWidth();
         int y=(int) yk.getScreenSize().getHeight();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("COST");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Cost");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 10, 196, 31);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Equipments");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 200, 173, 31);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Mike&Speakers");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 260, 106, 35);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(570, 260, 106, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Stage");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 310, 106, 35);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(570, 310, 106, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("DJ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(450, 360, 106, 35);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(570, 360, 106, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Decoration");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(840, 50, 150, 31);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Lightning");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(860, 300, 75, 33);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Delux");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(780, 400, 106, 35);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(910, 400, 106, 27);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Royal");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(780, 440, 106, 35);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField8);
        jTextField8.setBounds(910, 440, 106, 27);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Normal");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(780, 360, 110, 35);

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField9);
        jTextField9.setBounds(910, 360, 106, 28);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Flowers");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(860, 120, 75, 33);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Delux");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(780, 200, 106, 35);

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField10);
        jTextField10.setBounds(900, 200, 106, 27);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Royal");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(780, 240, 106, 35);

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField11);
        jTextField11.setBounds(900, 240, 106, 27);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Normal");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(780, 160, 106, 35);

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField12);
        jTextField12.setBounds(900, 160, 106, 28);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Sofa");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(770, 570, 106, 35);

        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13);
        jTextField13.setBounds(910, 570, 106, 27);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Chair&Sofa");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(770, 610, 106, 35);

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField14);
        jTextField14.setBounds(910, 610, 106, 27);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Chair");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(770, 530, 106, 35);

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField15);
        jTextField15.setBounds(910, 530, 106, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Seating");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(870, 490, 75, 33);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Update");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 450, 143, 35);

        jTextField16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField16);
        jTextField16.setBounds(210, 350, 106, 27);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Normal");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(90, 250, 70, 35);

        jTextField17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField17);
        jTextField17.setBounds(210, 250, 106, 28);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Food");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(160, 0, 80, 31);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Breakfast");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(150, 40, 75, 33);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Delux");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(100, 130, 80, 35);

        jTextField21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField21);
        jTextField21.setBounds(210, 130, 106, 27);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Royal");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(100, 170, 80, 40);

        jTextField22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField22);
        jTextField22.setBounds(210, 180, 106, 27);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("Normal");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(100, 80, 80, 35);

        jTextField23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField23);
        jTextField23.setBounds(210, 80, 106, 28);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Lunch");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(150, 220, 75, 33);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setText("Delux");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(90, 300, 70, 35);

        jTextField24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField24);
        jTextField24.setBounds(210, 300, 106, 27);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("Royal");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(90, 350, 60, 35);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setText("Dinner");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(150, 380, 75, 33);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setText("Delux");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(90, 460, 80, 35);

        jTextField25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField25);
        jTextField25.setBounds(210, 460, 106, 30);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setText("Royal");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(90, 500, 80, 35);

        jTextField26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField26);
        jTextField26.setBounds(210, 510, 106, 27);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setText("Normal");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(90, 410, 80, 35);

        jTextField27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField27);
        jTextField27.setBounds(210, 410, 106, 28);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Tea");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(90, 570, 50, 40);

        jTextField18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField18);
        jTextField18.setBounds(210, 580, 106, 28);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setText("Tea&Snacks");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(140, 540, 75, 33);

        setBounds(0, 0, 1160, 767);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String url="jdbc:mysql://localhost/eventdb";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{     
    String q="update cost set normalbreakfast=?,deluxbreakfast=?,royalbreakfast=?,normallunch=?,deluxlunch=?,royallunch=?,normaldinner=?,deluxdinner=?,royaldinner=?,tea=?,mike=?,stage=?,dj=?,simpleflower=?,deluxflower=?,royalflower=?,simplelight=?,deluxlight=?,royallight=?,chair=?,sofa=?,chairandsofa=?";
    PreparedStatement state=myconn.prepareStatement(q);
    state.setString(1, jTextField23.getText());
    state.setString(2, jTextField21.getText());
    state.setString(3, jTextField22.getText());
    state.setString(4, jTextField17.getText());
    state.setString(5, jTextField24.getText());
    state.setString(6, jTextField16.getText());
    state.setString(7, jTextField27.getText());
    state.setString(8, jTextField25.getText());
    state.setString(9, jTextField26.getText());
    state.setString(10, jTextField18.getText());
    state.setString(11, jTextField4.getText());
    state.setString(12, jTextField5.getText());
    state.setString(13, jTextField6.getText());
    state.setString(14, jTextField12.getText());
    state.setString(15, jTextField10.getText());
    state.setString(16, jTextField11.getText());
    state.setString(17, jTextField9.getText());
    state.setString(18, jTextField7.getText());
    state.setString(19, jTextField8.getText());
    state.setString(20, jTextField15.getText());
    state.setString(21, jTextField13.getText());
    state.setString(22, jTextField14.getText());
    int res=state.executeUpdate();
    if(res>0)
    {
 JOptionPane.showMessageDialog(rootPane, "Cost updated Succesfully");
 this.dispose();
// state.setString(1, jTextField17.getText());
//    state.setString(2,"");
//    state.setString(3, "");
//    state.setString(4,"");
//    state.setString(5, "");
//    state.setString(6, "");
//    state.setString(7, "");
//    state.setString(8, "");
//    state.setString(9, "");
//    state.setString(10, "");
//    state.setString(11, "");
//    state.setString(12, "");
//    state.setString(13, "");
//    state.setString(14, "");
//    state.setString(15, "");
//    state.setString(16, "");
//    state.setString(17, "");
//    state.setString(18, "");
//    state.setString(19,"");
//    state.setString(20, "");
//    state.setString(21, "");
//    state.setString(22,"");
    }
    else
    {
       JOptionPane.showMessageDialog(rootPane, "Cost NOT updated Succesfully");
//         state.setString(2,"");
//    state.setString(3, "");
//    state.setString(4,"");
//    state.setString(5, "");
//    state.setString(6, "");
//    state.setString(7, "");
//    state.setString(8, "");
//    state.setString(9, "");
//    state.setString(10, "");
//    state.setString(11, "");
//    state.setString(12, "");
//    state.setString(13, "");
//    state.setString(14, "");
//    state.setString(15, "");
//    state.setString(16, "");
//    state.setString(17, "");
//    state.setString(18, "");
//    state.setString(19,"");
//    state.setString(20, "");
//    state.setString(21, "");
//    state.setString(22,"");
    }
      
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "Fill all options please"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
      jButton2.setBackground(Color.GRAY);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
      jButton2.setBackground(Color.LIGHT_GRAY);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseExited

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
String url="jdbc:mysql://localhost/eventdb";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{
String q="select * from cost";
    PreparedStatement state=myconn.prepareStatement(q);
ResultSet res=state.executeQuery();
    if(res.next())
    {
      jTextField23.setText(res.getString("normalbreakfast"));
      jTextField21.setText(res.getString("deluxbreakfast"));
      jTextField22.setText(res.getString("royalbreakfast"));
      jTextField17.setText(res.getString("normallunch"));
      jTextField24.setText(res.getString("deluxlunch"));
      jTextField16.setText(res.getString("royallunch"));
      jTextField27.setText(res.getString("normaldinner"));
      jTextField25.setText(res.getString("deluxdinner"));
      jTextField26.setText(res.getString("royaldinner"));
      jTextField18.setText(res.getString("tea"));
      jTextField4.setText(res.getString("mike"));
      jTextField5.setText(res.getString("stage"));
      jTextField6.setText(res.getString("dj"));
      jTextField12.setText(res.getString("simpleflower"));
      jTextField10.setText(res.getString("deluxflower"));
      jTextField11.setText(res.getString("royalflower"));
      jTextField9.setText(res.getString("simplelight"));
      jTextField7.setText(res.getString("deluxlight"));
      jTextField8.setText(res.getString("royallight"));
      jTextField15.setText(res.getString("chair"));
      jTextField13.setText(res.getString("sofa"));
      jTextField14.setText(res.getString("chairandsofa"));
    }
    else
    {
        JOptionPane.showMessageDialog(rootPane, "fail"); 
    }
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}
   
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
