/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package event.management2;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author CS
 */
public class searchbookdeco extends javax.swing.JInternalFrame {
public String bookingid;

int b=0,l=0,s=0,x=0; /**
     * Creates new form booking
     */
    public searchbookdeco() {
        initComponents();
        
           Toolkit yk= Toolkit.getDefaultToolkit();
         int x=(int) yk.getScreenSize().getWidth();
         int y=(int) yk.getScreenSize().getHeight();
        jLabel13.setSize(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Booking Events");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("FOR BOOKING");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 30, 226, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("MemberID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 90, 128, 34);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 51, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(280, 90, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("BookingID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 140, 128, 34);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(280, 140, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Event Type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 190, 128, 50);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 51, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Marriage", "BirthdayParty", "FarewellParty", "FamilyFunction", "CollegeEvent", "AnniverseryParty", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 200, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Event Place");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 250, 128, 50);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(102, 51, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "PunjabPalace", "AbcGround", " ", " " }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(280, 260, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("Guests");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 310, 128, 50);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(280, 320, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 51, 0));
        jLabel9.setText("Date");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 370, 128, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 0));
        jButton1.setText("Calculate");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 340, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Decoration");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(590, 90, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Lightning");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(540, 140, 90, 30);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...select...", "No", "Simplelight", "Deluxlight", "Royallight", " " }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(650, 140, 140, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 51, 0));
        jLabel10.setText("Flowers");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(540, 190, 90, 30);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...select...", "No", "Simpleflower", "Deluxflower", "Royalflower" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(650, 190, 140, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 51, 0));
        jLabel11.setText("Seating");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(540, 240, 90, 30);

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...select...", "Chair", "Sofa", "ChairandSofa" }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(650, 240, 140, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\CS\\Desktop\\images (3).jpg")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, -20, 10, 10);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 51, 0));
        jButton2.setText("BACK");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 433, 110, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(280, 380, 150, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\CS\\Desktop\\images (7).jpg")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1028, 615);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  String url="jdbc:mysql://localhost/eventdb";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{
 Date f=jDateChooser1.getDate();
   Date cur=new Date();
     if(jComboBox1.getSelectedIndex()==0 || jComboBox2.getSelectedIndex()==0  || (f.compareTo(cur)<0) || jDateChooser1.getDate()==(null)|| jTextField2.getText().equalsIgnoreCase("") ||jTextField1.getText().equalsIgnoreCase("")||jTextField3.getText().equalsIgnoreCase(""))
    {
        if(jDateChooser1.getDate()==null)
        {
JOptionPane.showMessageDialog(rootPane, "Choose Date");
        }
        else if((f.compareTo(cur)<0)) 
    {
JOptionPane.showMessageDialog(rootPane, "Date is wrong");
    }
        else
        {     
JOptionPane.showMessageDialog(rootPane, "Please fill full info..");
        }
    }
        else
       {
           String o="select * from addmember where memberid=?";
       
       
             PreparedStatement state1=myconn.prepareStatement(o);
             state1.setString(1, jTextField1.getText());
             ResultSet res1=state1.executeQuery();

             if(res1.next())
             {
    String q="update booking set memberid=?,type=?,place=?,guests=?,date=?,light=?,flower=?,seating=? where bookingid=?";
    PreparedStatement state=myconn.prepareStatement(q);
    state.setString(1, jTextField1.getText());   
    state.setString(2, jComboBox1.getSelectedItem().toString());
    state.setString(3, jComboBox2.getSelectedItem().toString());
    state.setString(4, jTextField3.getText()); 
  
    SimpleDateFormat mydate=new SimpleDateFormat("yyyy-MM-dd");
    String ob=mydate.format(jDateChooser1.getDate());
    state.setString(5, ob); 
 
String eq="";

if(jComboBox3.getSelectedIndex()==0)
{
   JOptionPane.showMessageDialog(rootPane, "Choose Lightining option"); 
}
else
{
    l=1;
state.setString(6, jComboBox3.getSelectedItem().toString());
}
if(jComboBox4.getSelectedIndex()==0)
{
   JOptionPane.showMessageDialog(rootPane, "Choose Flowering option"); 
}

else
{
   b=1; 
state.setString(7, jComboBox4.getSelectedItem().toString());
}
if(jComboBox5.getSelectedIndex()==0)
{
   JOptionPane.showMessageDialog(rootPane, "Choose seating option"); 
}

else
{
    s=1;
state.setString(8, jComboBox5.getSelectedItem().toString());
}

    state.setString(9, jTextField2.getText()); 
   
    String r2="select date from booking where date =?";
    PreparedStatement state3=myconn.prepareStatement(r2);
    SimpleDateFormat mydate7=new SimpleDateFormat("yyyy-MM-dd");
    String ob7=mydate7.format(jDateChooser1.getDate());
    state3.setString(1, ob7); 
    ResultSet res3=state3.executeQuery();
    String h;
    if(res3.next())
    { 
        
    String p=jComboBox2.getSelectedItem().toString();
   int k=Integer.parseInt(jTextField2.getText());
   String st1="";
   String r3="select * from booking where date=?";
   PreparedStatement state9=myconn.prepareStatement(r3);
   state9.setString(1,ob7);
   ResultSet res8=state9.executeQuery();
   while(res8.next())
   {
     if(k!=res8.getInt("bookingid"))
     {
        st1=st1+res8.getString("place");
     }
   } 
   if(st1.toLowerCase().contains(p))
   {  
     JOptionPane.showMessageDialog(rootPane, "**Please Change Venue OR Date**");  
   }
   else
   {
       int res;
  if(l==1 && s==1 && b==1)   
 res=state.executeUpdate();
 else
  {
      x=1;
      res=0;
  }
if(res>0)
{
          JOptionPane.showMessageDialog(rootPane, "Booking updated Succesfully");
          searchbookbill obj = new searchbookbill();
          obj.bookingid=jTextField2.getText();
          mainform.jDesktopPane2.add(obj);
          obj.setVisible(true);
          this.dispose();  
}
else
{
    if(x!=1)
       JOptionPane.showMessageDialog(rootPane, "Booking not updated Succesfully");
}
   }
    }
    
    
    else
    {
          int res;
  if(l==1 && s==1 && b==1)   
 res=state.executeUpdate();
 else
  {
      x=1;
      res=0;
  }
      
   if(res>0)
    { 
     // JOptionPane.showMessageDialog(rootPane, "Member  Updated Succesfully date hi nhi si database vich");
      JOptionPane.showMessageDialog(rootPane, "Booking updated Succesfully");
          searchbookbill obj = new searchbookbill();
          obj.bookingid=jTextField2.getText();
          mainform.jDesktopPane2.add(obj);
          obj.setVisible(true);
          this.dispose();
    }
      else
   {  if(x!=1)
       JOptionPane.showMessageDialog(rootPane, "error");
     //JOptionPane.showMessageDialog(rootPane, "Member not updated Succesfully date hi nhi si database vich");  
   }   
    }
      
             }
             else
             {
       JOptionPane.showMessageDialog(rootPane, "member id not available");
                 
             }
       }
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}

  
  


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

        String url="jdbc:mysql://localhost/eventdb";
       try
       {
           Connection myconn=DriverManager.getConnection(url, "root", "");
           try
           {
             String q="select * from booking where bookingid=?";
             PreparedStatement state=myconn.prepareStatement(q);
             state.setString(1, bookingid);
             ResultSet res=state.executeQuery();
             if(res.next())
             {                         
    String q1="select * from addvenues";
    PreparedStatement state2=myconn.prepareStatement(q1);
    ResultSet res2=state2.executeQuery();
 
while(res2.next())
{
    jComboBox2.addItem(res2.getString("name"));
}
if(jComboBox2.getItemCount()==1)
{
    jComboBox2.removeAllItems();
    jComboBox2.addItem("no venue");
}

  String q2="select * from addevent";
    PreparedStatement state3=myconn.prepareStatement(q2);
    ResultSet res3=state3.executeQuery();
while(res3.next())
{
    jComboBox1.addItem(res3.getString("name"));
}
if(jComboBox1.getItemCount()==1)
{
    jComboBox1.removeAllItems();
    jComboBox1.addItem("no event");
}
           
                 jTextField1.setText(res.getString("memberid"));
                 jTextField2.setText(res.getString("bookingid"));
                 jTextField3.setText(res.getString("guests"));
                 jDateChooser1.setDate(res.getDate("date"));
                 jComboBox1.setSelectedItem(res.getString("type")); 
                 jComboBox2.setSelectedItem(res.getString("place"));
                 if(res.getString("light").equalsIgnoreCase("") && res.getString("flower").equalsIgnoreCase("") && res.getString("seating").equalsIgnoreCase("") )
                 {
                     jComboBox3.setSelectedIndex(0);
                     jComboBox4.setSelectedIndex(0);
                     jComboBox5.setSelectedIndex(0);
                 }
               else
                 {
                     jComboBox3.setSelectedItem(res.getString("light"));
                     jComboBox4.setSelectedItem(res.getString("flower"));
                     jComboBox5.setSelectedItem(res.getString("seating")); 
                 }
             }
             else
             {
                 JOptionPane.showMessageDialog(rootPane, "Invalid Booking Id"); 
                 jTextField2.setText("");
             }
           }
                 catch(Exception e)
                    {
              JOptionPane.showMessageDialog(rootPane, "Error in Query"+e.getMessage());
                    }
       }
       catch(SQLException e)
       {
           JOptionPane.showMessageDialog(rootPane, "Error in Connection"+e.getMessage());
       }       
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
jButton1.setBackground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
jButton1.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
jButton2.setBackground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
jButton2.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       searchbookfood obj = new searchbookfood();
          obj.bookingid=jTextField2.getText();
        
          mainform.jDesktopPane2.add(obj);
          obj.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
