/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package event.management2;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author CS
 */
public class searchbookpaymode extends javax.swing.JInternalFrame {
public String bookingid;
public int amount;
public int required;
int d=0;
/**
     * Creates new form bookingpaymode
     */
    public searchbookpaymode() {
        initComponents();
       
           Toolkit yk= Toolkit.getDefaultToolkit();
         int x=(int) yk.getScreenSize().getWidth();
         int y=(int) yk.getScreenSize().getHeight();
         jLabel9.setSize(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pay Mode");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 0));
        jButton1.setText("PAY");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 580, 93, 36);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(390, 120, 152, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("BookingID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 120, 142, 29);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(102, 51, 0));
        jRadioButton1.setText("Cash");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(170, 280, 94, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(102, 51, 0));
        jRadioButton2.setText("Debit/Credit Card");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(590, 270, 186, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("PAYMENT MODE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 60, 180, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Choose Options");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 180, 140, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Card Details"));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("CardNo.");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 30, 117, 24);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 51, 0));
        jPanel2.add(jTextField1);
        jTextField1.setBounds(210, 30, 156, 32);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("CVVNo.");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 80, 117, 24);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 51, 0));
        jPanel2.add(jTextField2);
        jTextField2.setBounds(210, 80, 156, 32);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Nameoncard");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 130, 117, 24);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 51, 0));
        jPanel2.add(jTextField3);
        jTextField3.setBounds(210, 130, 156, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("ExperitionDate");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 180, 117, 24);
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(210, 180, 150, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(490, 320, 390, 250);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(102, 51, 0));
        jRadioButton3.setText("Full Payment");
        jRadioButton3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton3ItemStateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(260, 180, 120, 23);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(102, 51, 0));
        jRadioButton4.setText("Instalments");
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(460, 180, 120, 23);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(102, 51, 0));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(620, 220, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("Ist Installment/Advance Money");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 210, 230, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\CS\\Desktop\\images (7).jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1024, 689);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(!jRadioButton3.isSelected() && !jRadioButton4.isSelected())
        {    
    JOptionPane.showMessageDialog(rootPane, "Choose Options of amount");
        }
        if(!jRadioButton1.isSelected() && !jRadioButton2.isSelected())
        {    
    JOptionPane.showMessageDialog(rootPane, "Choose mode");
        }
        
        else//((!jRadioButton1.isSelected() && !jRadioButton2.isSelected()) || (!jRadioButton3.isSelected() && !jRadioButton4.isSelected())) 
        {
        String url="jdbc:mysql://localhost/eventdb";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{       
   
    String q="update booking set paymode=?,cardno=?,cvvno=?,cardname=?,expiredate=?,amountpaid=?,paymentstatus=?,pendingrs=? where bookingid=?";
    PreparedStatement state=myconn.prepareStatement(q);
    if(jRadioButton3.isSelected())
    {    
if(jRadioButton1.isSelected())
{
        state.setString(1, "cash");
        state.setString(2, "");
        state.setString(3, "");
        state.setString(4, "");
    Date c=new Date();
    SimpleDateFormat mydate4=new SimpleDateFormat("yyyy-MM-dd");
    String ob4=mydate4.format(c);
        state.setString(5, ob4);
        state.setString(6, String.valueOf(amount));
        state.setString(7, "notpending");
        state.setString(8, String.valueOf(0));
        d=0;
}
else if(jRadioButton2.isSelected())
{
    
 Date f=jDateChooser1.getDate();
   Date cur=new Date();
     if(jTextField1.getText().toString().equalsIgnoreCase("") ||jTextField2.getText().toString().equalsIgnoreCase("") ||
      jTextField3.getText().toString().equalsIgnoreCase("") || jDateChooser1.getDate()==(null))
    {  
      JOptionPane.showMessageDialog(rootPane, "fill all details of card");  
      d=1;
          if((f.compareTo(cur)<=0)) 
         {
       JOptionPane.showMessageDialog(rootPane, "Date is wrong");
       d=1;
         }
    }
    else
         {          
        state.setString(1, "online");
        state.setString(2,jTextField1.getText());
        state.setString(3,jTextField2.getText());
        state.setString(4,jTextField3.getText());
    SimpleDateFormat mydate=new SimpleDateFormat("yyyy-MM-dd");
    String ob=mydate.format(jDateChooser1.getDate());
    state.setString(5, ob); 
        state.setString(6, String.valueOf(amount));
        state.setString(7, "notpending");
        state.setString(8, String.valueOf(0));
        d=0;
         }
}    
    }
    else if(jRadioButton4.isSelected())
    {
if(jRadioButton1.isSelected())
{
    int pending=amount-required;
        state.setString(1, "cash");
        state.setString(2, "");
        state.setString(3, "");
        state.setString(4, "");
    Date c=new Date();
    SimpleDateFormat mydate4=new SimpleDateFormat("yyyy-MM-dd");
    String ob4=mydate4.format(c);
        state.setString(5, ob4);
        state.setString(6, jTextField6.getText());
        state.setString(7, "pending");
        state.setString(8,String.valueOf(pending));
        d=0;
}
else if(jRadioButton2.isSelected())
{
 Date f=jDateChooser1.getDate();
   Date cur=new Date();
    int pending2=amount-required;
     if(jTextField1.getText().toString().equalsIgnoreCase("") ||jTextField2.getText().toString().equalsIgnoreCase("") ||
      jTextField3.getText().toString().equalsIgnoreCase("") ||jDateChooser1.getDate()==(null))
    {  
      JOptionPane.showMessageDialog(rootPane, "fill all details of card");  
      d=1;
      
          if((f.compareTo(cur)<=0)) 
         {
       JOptionPane.showMessageDialog(rootPane, "Date is wrong");
       d=1;
         }
    }
    else
         {          
        state.setString(1, "online");
        state.setString(2,jTextField1.getText());
        state.setString(3,jTextField2.getText());
        state.setString(4,jTextField3.getText());
    SimpleDateFormat mydate=new SimpleDateFormat("yyyy-MM-dd");
    String ob=mydate.format(jDateChooser1.getDate());
    state.setString(5, ob); 
        state.setString(6, jTextField6.getText());
        state.setString(7, "pending");
        state.setString(8,String.valueOf(pending2));
        d=0;
         } 
}
    }
        state.setString(9, jTextField5.getText());
    
       int res=state.executeUpdate();
        if(res>0 && d==0)
        {
      JOptionPane.showMessageDialog(rootPane, "Payment paid Successfully");
          searchnewbill obj = new searchnewbill();
          obj.bookingid=jTextField5.getText();
          obj.fullamount=amount;
          mainform.jDesktopPane2.add(obj);
          obj.setVisible(true);
         this.dispose();  
         }
        else
        { 
      if(d!=0)
      JOptionPane.showMessageDialog(rootPane, "Error in payment transaction");   
        }
}
catch(Exception e)
{
    if(d!=1)
          JOptionPane.showMessageDialog(rootPane, "error in querys"+e.getMessage());
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}
       

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
      
        jTextField5.setText(bookingid);
jRadioButton1.setVisible (false);
jRadioButton2.setVisible (false);
jTextField6.setText(String.valueOf(required));

                jPanel2.setVisible(false);
                jTextField6.setVisible(false);
                jLabel8.setVisible(false);
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
jButton1.setBackground(Color.GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
jButton1.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
       if(jRadioButton2.isSelected())
          jPanel2.setVisible(true);
       else
          jPanel2.setVisible(false);
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged
        if(jRadioButton4.isSelected())
        {
            jLabel8.setVisible(true);
            jTextField6.setVisible(true);
            jRadioButton1.setVisible(true);
            jRadioButton2.setVisible(true);
        }
        else
        {
            jLabel8.setVisible(false);
            jTextField6.setVisible(false);
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ItemStateChanged

    private void jRadioButton3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton3ItemStateChanged
                                                     
        if(jRadioButton3.isSelected())
        {
            jRadioButton1.setVisible(true);
            jRadioButton2.setVisible(true);
        }
        else
        {
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
