/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package event.management2;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author CS
 */
public class searchbookbill extends javax.swing.JInternalFrame {
public String bookingid;
int paid,result;
    /**
     * Creates new form booking
     */
    public searchbookbill() {
        initComponents();
        
           Toolkit yk= Toolkit.getDefaultToolkit();
         int x=(int) yk.getScreenSize().getWidth();
         int y=(int) yk.getScreenSize().getHeight();
          jLabel17.setSize(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Booking Events");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("MemberID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 150, 128, 34);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 51, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 150, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("BookingID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 200, 128, 34);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(270, 200, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Event Type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 250, 128, 50);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 51, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(270, 260, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Event Place");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 310, 128, 50);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(102, 51, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(270, 320, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("Guests");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 370, 128, 50);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(270, 380, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 51, 0));
        jLabel9.setText("Date");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 430, 128, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 480, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Total Amount");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 140, 140, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 51, 0));
        jLabel12.setText("...........");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(710, 130, 130, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 51, 0));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 440, 100, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(270, 440, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Final Information of booking ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 40, 300, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("..........");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(590, 40, 100, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tax");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 180, 70, 30);

        jLabel11.setText("...........");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(710, 190, 150, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 51, 0));
        jLabel13.setText("Net Amount");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(520, 230, 140, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 51, 0));
        jLabel14.setText("...........");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(710, 220, 130, 50);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 51, 0));
        jLabel15.setText("Required Amount");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(520, 280, 140, 40);

        jLabel16.setText(".............");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(710, 290, 100, 14);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 51, 0));
        jLabel19.setText("Previous Submit Amount");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(520, 330, 190, 30);

        jLabel20.setText("........................................");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(710, 340, 100, 14);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 51, 0));
        jLabel21.setText("Net Submit Amount");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(520, 370, 190, 30);

        jLabel22.setText("....................");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(710, 380, 90, 14);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\CS\\Desktop\\images (7).jpg")); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1028, 615);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(jComboBox1.getSelectedIndex()==0||jComboBox2.getSelectedIndex()==0)
{
    if(jComboBox1.getSelectedIndex()==0)
    JOptionPane.showMessageDialog(rootPane,"First Add Event");
    else
    JOptionPane.showMessageDialog(rootPane,"First Add Venues");
}
else
{
    

        String url="jdbc:mysql://localhost/eventdb";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{   
   String o="select * from addmember where memberid=?";
       
       
             PreparedStatement state1=myconn.prepareStatement(o);
             state1.setString(1, jTextField1.getText());
             ResultSet res1=state1.executeQuery();

             if(res1.next())
             {
    String q="update booking set amount=? where bookingid=?";
    PreparedStatement state=myconn.prepareStatement(q);
    state.setString(1, jLabel14.getText());
    state.setString(2,jTextField2.getText());
    int res=state.executeUpdate();
        if(res>0 )
        {
         JOptionPane.showMessageDialog(rootPane, "Bill made Succesfully");
          searchbookbill2 obj = new searchbookbill2();
          obj.bookingid=jTextField2.getText();
          obj.amountsubmit=Integer.parseInt(jLabel14.getText());
          obj.requiredamount=Integer.parseInt(jLabel22.getText());
          
//          
//           bookingpaymode o=new bookingpaymode();
//           o.required=Integer.parseInt(jLabel16.getText());
          mainform.jDesktopPane2.add(obj);
          obj.setVisible(true);
          this.dispose(); 
        }
        else
        { 
            
      JOptionPane.showMessageDialog(rootPane, "Error in bill made");   
        }
             }
             else
             {
                      JOptionPane.showMessageDialog(rootPane, "member id not available");   
                      
             }
}
catch(Exception e)
{
      JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage()); 
}
finally
    {
      myconn.close();      
    }
}
catch(SQLException e)
{
    JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
}
       
}         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

        String url="jdbc:mysql://localhost/eventdb";
       try
       {
           Connection myconn=DriverManager.getConnection(url, "root", "");
           try
           {
               String q1="select * from addvenues";
    PreparedStatement state5=myconn.prepareStatement(q1);
    ResultSet res5=state5.executeQuery();
 
while(res5.next())
{
    jComboBox2.addItem(res5.getString("name"));
}
if(jComboBox2.getItemCount()==1)
{
    jComboBox2.removeAllItems();
    jComboBox2.addItem("no venue");
}  String q2="select * from addevent";
    PreparedStatement state3=myconn.prepareStatement(q2);
    ResultSet res3=state3.executeQuery();
while(res3.next())
{
    jComboBox1.addItem(res3.getString("name"));
}
if(jComboBox1.getItemCount()==1)
{
    jComboBox1.removeAllItems();
    jComboBox1.addItem("no event");
}
             String q="select * from booking where bookingid=?";
             String c="select * from cost";
             PreparedStatement state=myconn.prepareStatement(q);
             PreparedStatement state2=myconn.prepareStatement(c);
             state.setString(1, bookingid);
             ResultSet res=state.executeQuery();
             ResultSet res2=state2.executeQuery();
        
             if(res.next() && res2.next())
             {      
                 jLabel10.setText(bookingid);
                 jLabel20.setText(res.getString("amountpaid"));
                 paid=res.getInt("amountpaid");
                 
                 int venue,eq=0,food=0,deco=0,gue=0;
                 gue=res.getInt("guests");
                 venue=res.getInt("costvenue");
                 if(res.getString("equipments").equals("mike&speaker"))
                 {
                   eq=eq+res2.getInt("mike");
                 }  
                 if(res.getString("equipments").equals("dj"))
                 {
                   eq=eq+res2.getInt("dj");
                 }  
                 if(res.getString("equipments").equals("stage"))
                 {
                   eq=eq+res2.getInt("stage");
                 }  
                 if(res.getString("equipments").equals("dj,mike&speaker"))
                 {
                   eq=eq+res2.getInt("dj")+res2.getInt("mike");
           
                 }  
                 if(res.getString("equipments").equals("dj,stage"))
                 {
                   eq=eq+res2.getInt("dj")+res2.getInt("stage");
                   
                 }  
                 if(res.getString("equipments").equals("mike&speaker,stage"))
                 {
                   eq=eq+res2.getInt("mike")+res2.getInt("stage");
                   
                 }  
                 if(res.getString("equipments").equals("dj,mike&speaker,stage"))
                 {
                   eq=eq+res2.getInt("mike")+res2.getInt("stage")+res2.getInt("dj");
                 } 
                 
                 String br=res.getString("breakfast");
                 if(br.equalsIgnoreCase("no"))
                     food=food;
                 else
                     food=(food+res2.getInt(br))*gue;
                 
                
                 String lu=res.getString("lunch");
                 if(lu.equalsIgnoreCase("no"))
                     food=food;
                 else
                     food=(food+res2.getInt(lu))*gue;
                 
                
                 String di=res.getString("dinner");
                 if(di.equalsIgnoreCase("no"))
                     food=food;
                 else
                     food=(food+res2.getInt(di))*gue;
                 
                  String te=res.getString("tea");
                       if(te.equalsIgnoreCase("no"))
                     food=food;
                       else 
                     food=food+res2.getInt("tea");
                      
                       String li=res.getString("light");
                       if(li.equalsIgnoreCase("no"))
                       deco=deco;
                       else
                       deco=deco+res2.getInt(li);
                    
                       String fl=res.getString("flower");
                       if(fl.equalsIgnoreCase("No"))
                       deco=deco;
                       else
                       deco=deco+res2.getInt(fl);
                     
                       String ch=res.getString("seating");
                       if(ch.equalsIgnoreCase("no"))
                       deco=deco;
                       else
                       deco=deco+res2.getInt(ch);
                       
                      int amount=venue+food+deco+eq;
                      
                      int tax=(10*amount)/100;
                      int re=((amount+tax)*30)/100;
                       jLabel12.setText(String.valueOf(amount));
                       jLabel11.setText(String.valueOf(tax));
                       jLabel14.setText(String.valueOf(amount+tax));
                       jLabel16.setText(String.valueOf(re));
                      result=re-paid;
                       if(result<0)
                           result=0;
                       
                       jLabel22.setText(String.valueOf(result));
      
             }
             else
             {
                 JOptionPane.showMessageDialog(rootPane, "Invalid bookingid"); 
             }
           }
                 catch(Exception e)
                    {
              JOptionPane.showMessageDialog(rootPane, "Error in Query"+e.getMessage());
                    }
       }
       catch(SQLException e)
       {
           JOptionPane.showMessageDialog(rootPane, "Error in Connection"+e.getMessage());
       }

       try
       {
           Connection myconn=DriverManager.getConnection(url, "root", "");
           try
           {
             String q1="select * from booking where bookingid=?";
             PreparedStatement state=myconn.prepareStatement(q1);
             state.setString(1, bookingid);
             ResultSet res3=state.executeQuery();
             if(res3.next())
             {
                 jTextField1.setText(res3.getString("memberid"));
                 jTextField2.setText(res3.getString("bookingid"));
                 jTextField3.setText(res3.getString("guests"));
                 jDateChooser1.setDate(res3.getDate("date"));
                 jComboBox1.setSelectedItem(res3.getString("type")); 
                 jComboBox2.setSelectedItem(res3.getString("place")); 
             }
             else
             {
                 JOptionPane.showMessageDialog(rootPane, "Invalid Booking Id"); 
                 jTextField2.setText("");
             }
           }
                 catch(Exception e)
                    {
              JOptionPane.showMessageDialog(rootPane, "Error in Query"+e.getMessage());
                    }
       }
       catch(SQLException e)
       {
           JOptionPane.showMessageDialog(rootPane, "Error in Connection"+e.getMessage());
       }       
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
                            bookingdeco obj = new bookingdeco();
                            obj.bookingid=jTextField2.getText();
                            obj.d=2;
                            mainform.jDesktopPane2.add(obj);
                            obj.setVisible(true);
                            this.dispose();
                            
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
