/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package event.management2;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author CS
 */
public class venue3 extends javax.swing.JInternalFrame {

    /**
     * Creates new form venue3
     */
    public venue3() {
        initComponents();
           Toolkit yk= Toolkit.getDefaultToolkit();
         int x=(int) yk.getScreenSize().getWidth();
         int y=(int) yk.getScreenSize().getHeight();
      //   jLabel3.setSize(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        label4 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label7 = new java.awt.Label();

        setBackground(new java.awt.Color(204, 204, 204));
        setTitle("view venue");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 150, 213, 188);

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Venue name" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(30, 90, 213, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View Venue");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(299, 19, 263, 29);

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Details of Venue");
        getContentPane().add(label4);
        label4.setBounds(570, 30, 113, 20);

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 51, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Phone", "Guests", "Cost"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(360, 70, 560, 510);

        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText("Image of venue");
        getContentPane().add(label7);
        label7.setBounds(110, 370, 113, 20);

        setBounds(0, 0, 1265, 633);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    try
    {
        String url="jdbc:mysql://localhost/eventdb";
        Connection myconn=DriverManager.getConnection(url, "root", "");
        try
        {
               DefaultTableModel mymodel1=(DefaultTableModel)jTable1.getModel();
               mymodel1.setRowCount(0);
            String q="select * from addvenues where name=?";
            
            PreparedStatement state=myconn.prepareStatement(q);
       state.setString(1, jComboBox1.getSelectedItem().toString());
            ResultSet res=state.executeQuery();
           if(res.next())
           {
       //DefaultTableModel mymodel1=(DefaultTableModel)jTable1.getModel();
         //    mymodel1.removeRow(0);
               String mid=res.getString("name");
               String bid=res.getString("address");
               String type=res.getString("phone");
               String place=res.getString("capacity");
               String g=res.getString("cost");  
               String ofile=(res.getString("image"));
                   ofile=res.getString("image");
Image simg = ImageIO.read( new File(ofile)).getScaledInstance( jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_DEFAULT);
 jLabel2.setIcon(new ImageIcon(simg)); 
               DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
               Object myrow[]={mid,bid,type,place,g};
               mymodel.addRow(myrow);
           }
            if(jTable1.getRowCount()==0)
               {
                   JOptionPane.showMessageDialog(rootPane,"no venues found");
               }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage());
        }
    }
    catch(SQLException e)
    {
       JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
    }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
fetch();        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged


//    try
//    {
//        String url="jdbc:mysql://localhost/eventdb";
//        Connection myconn=DriverManager.getConnection(url, "root", "");
//        try
//        {
//            String q="select * from addvenues where name=?";
//            
//            PreparedStatement state=myconn.prepareStatement(q);
//            ResultSet res=state.executeQuery();
//           while(res.next())
//           {
//               String mid=res.getString("name");
//               String bid=res.getString("address");
//               String type=res.getString("phone");
//               String place=res.getString("capacity");
//               String g=res.getString("cost");
//               DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
//               Object myrow[]={mid,bid,type,place,g};
//               mymodel.addRow(myrow);
//              
//           }
//            if(jTable1.getRowCount()==0)
//               {
//                   JOptionPane.showMessageDialog(rootPane,"no venues found");
//               }
//        }
//        catch(Exception e)
//        {
//            JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage());
//        }
//    }
//    catch(SQLException e)
//    {
//       JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
//    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged
void fetch()
{
      
        String url="jdbc:mysql://localhost/eventdb";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{
    String q1="select * from addvenues";
    PreparedStatement state2=myconn.prepareStatement(q1);

    ResultSet res2=state2.executeQuery();
    
while(res2.next())
{
    jComboBox1.addItem(res2.getString("name"));
}
if(jComboBox1.getItemCount()==1)
{
    jComboBox1.removeAllItems();
    jComboBox1.addItem("no venue");
}
}
catch(Exception e)
{
   JOptionPane.showMessageDialog(rootPane, "error in bookid");  
}
}
catch(SQLException e)
{
   JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());  
}

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.awt.Label label4;
    private java.awt.Label label7;
    // End of variables declaration//GEN-END:variables
}
